### ISSUE TITLE
QoL Improvements

### ISSUE THREAD

**Issue by GhostlyDark** [marcrobledo/minidex#2]
Here are some improvements/fixes I want to suggest. I can work on some of them myself, though I am not that familiar with the code (yet).

- [x] **Back button:** Changing the game currently requires the user to scroll down to the bottom and click on "More games" which opens the "welcome page" in a new tab. I suggest having a back button at the top left of the page which brings one back to the initial page. That button and the language selector could be position:fixed (at least on Desktop).
- [x] **Improve lang selection:** The language selection seems a bit buggy right now. It doesn't save on the initial page, does not instantly update Pokémon names ~~and doesn't save the Japanese language (jumps back to English upon reload)~~.
- [x] **Global lang setting:** The user should only have to set the preferred language a single time. It should be one global value instead of seperate language settings for each game page.
- [ ] **index.html not fully translated:** All of the index.html files have text blocks that can't be translated right now.
- [ ] **Make caught button available to all Pokémon:** The button isn't there for some of the Pokémon in the national dex and that makes it impossible to mark them as being caught.
- [x] **Get rid of inline CSS and JS:** Low priority.

**Comment by GhostlyDark** [comment]
Progress is made here:
https://github.com/GhostlyDark/minidex/tree/QoL

**Comment by marcrobledo** [comment]
First of all, thanks for your recent contributions :-) I coded this for my friends and me, I didn't expect anyone else interested on this.

- **Back button:** instead of a back button, I suggest a dropdown menu (or a popup) so you can switch between games with a single click/tap. That was my initial idea, but had to add that dirty link at the bottom due to lack of time.
- **Improve lang selection:** I was aware of that, but it wasn't a priority as there were no french/deutsch translations. That has changed, however ;-)
- **Global lang setting:** makes sense, good idea!
- **index.html not fully translated:** I didn't understand this one. All HTML strings are replaced and localized when the page is loaded so you could even remove them and it wouldn't make any difference. I left them for SEO purposes.
- **Make caught button available to all Pokémon:** this is intended. I figured it didn't make sense to mark any Pokémon that needs transfer from older generation or other games. However, they still show up for competitive info (well, until Let's go, as National dex is gone). I would prefer to keep it this way.

Anyway, thanks again, but I can't promise any work on Minidex on my side for now, I'm a little busy lately. Feel free to update your branch and request pulls for any language related edits. If you don't mind, I'd like to implement my own 'back' button as it was indeed on my initial plans.

**Comment by GhostlyDark** [comment]
The page with all the games on it gets no translated "Developed by..." and "View on GitHub" text. The disclaimer at the bottom is always English. It's really minor though.

One thing I noticed in the meantime is that the forceGoToHome() function does not seem to work on mobile (using a Chromium based Browser). I assume it's the window.history not working at all as I had issues getting that to work in the past.

**Comment by marcrobledo** [comment]
I'm rearranging the localization system, adding/fixing missing translations to all locations across all games and more :-)

**Comment by marcrobledo** [comment]
I will have this up tomorrow.

**Comment by marcrobledo** [comment]
It has been updated at last! With a cool new menu button in the top left corner. Right now it allows you to change game or language (which is the same for all games now!), but it could get new features in a future.

**Comment by GhostlyDark** [comment]
Nice! That definitely fixes my main complaints.
